version: "3"
services:
  nifi:
    image: apache/nifi
    container_name: nifi
    volumes:
      - /home/thanhnp/projects/learning/nifi/conf:/opt/nifi/conf
    ports:
      - 8443:8443
    environment:
      NIFI_WEB_HTTPS_PORT: '8443'
      NIFI_WBE_HTTP_HOST: '0.0.0.0'
      NIFI_WEB_PROXY_HOST: '0.0.0.0:8443'
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    restart: always
